name: Deploy Land DA Container

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: jitterbit/get-changed-files@v1
      id: abc
      with:
        format: space-delimited
        token: ${{ secrets.GITHUB_TOKEN }}        
          
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build, tag, and push image to DockerHub
      run: |
        # Build Docker container and push and deploy to Docker
        echo "maximize disk space on git-runner ..."
        df -h 
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h
        echo "docker build ..."
        #docker run -d --tmpfs /run:rw,noexec,nosuid,size=65536k noaaepic/ubuntu20.04-intel-landda:develop
        docker build -t ufs-noahmp_landa:develop .
        df -h

    - name: docker push tag ufs-noahmp_landa:develop
      run: | 
       echo "docker push ..."
       docker push jongkim2004/ufs-noahmp_landa:develop
        
    - name: docker logout
      run: |
       docker logout
