name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'

    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build the Docker image
      run: source ./free_runner_spcae.sh; docker system prune; docker build --no-cache --compress . --file Dockerfile --tag my-image-name:$(date +%s)
